# Pipeline de la integracion Customers.

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src/integrations/customers/AxxonCustomers.Functions/**
      - src/core/**
      - pipelines/azure-pipelines-customers.yml
      - pipelines/templates/functionapp-build-deploy.yml

variables:
  - name: azureServiceConnection
    value: 'sc-chacomer-eip-inte'
  - name: environmentName
    value: 'inte'

extends:
  template: templates/functionapp-build-deploy.yml
  parameters:
    appName: 'fa-axxoncustomers-$(environmentName)'
    projectPath: 'src/integrations/customers/AxxonCustomers.Functions/AxxonCustomers.Functions.csproj'
    azureServiceConnection: '$(azureServiceConnection)'
    environmentName: '$(environmentName)'
