# Pipeline de la integracion Customers.

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src/integrations/customers/AxxonCustomers.Functions/**
      - src/core/**
      - tests/AxxonCustomers.Functions.Tests/**
      - pipelines/azure-pipelines-customers.yml
      - pipelines/templates/functionapp-build-deploy.yml
      - pipelines/templates/functionapp-deploy-stage.yml

extends:
  template: templates/functionapp-build-deploy.yml
  parameters:
    appBaseName: 'fa-axxoncustomers'
    projectPath: 'src/integrations/customers/AxxonCustomers.Functions/AxxonCustomers.Functions.csproj'
    testProjectPath: 'tests/AxxonCustomers.Functions.Tests/AxxonCustomers.Functions.Tests.csproj'
